cameratrap/urls.py
from django.urls import path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from cameratrap import views

app_name = 'cameratrap'
urlpatterns = [
    #path('', views.index, name='index'),
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('uploads/', views.UploadFileView, name='upload'),
    path("<int:video_pkid>/process", views.SyncProcessVideoView, name='process'),
    path("<int:video_pkid>/asyncprocess", views.ASyncProcessVideoView, name='asyncprocess'),
    path("<int:video_pkid>/<int:video_frame_pkid>/coco", views.CocoVideoFrameView, name='coco'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('cameratrap/', include('cameratrap.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

cameratrap/models.py
from django.db import models
import ntpath
from django.utils.translation import gettext_lazy as _
from django.utils.text import slugify

class VideoFile(models.Model):

    def __str__(self):
        return self.filename

    class VideoStatus(models.TextChoices):
        NONE = 'NON', _('None')
        UPLOADED = 'UPL', _('Uploaded')
        PROCESSING = 'PRO', _('Processing')
        REPROCESS = 'REP', _('Flagged for Reprocessing')
        COMPLETED = 'CPL', _('Completed')

    def video_status_readable(self) -> VideoStatus:
        # Get value from choices enum
        return self.VideoStatus(self.video_status).label

    def fn_video_location(instance, filename):
        return '/'.join(['videos', slugify(instance.site_id), slugify(instance.ct_id), filename])

    ct_id = models.CharField(max_length=20)
    site_id = models.CharField(max_length=20)
    date_start = models.DateTimeField('start date', null=True, blank=True)
    date_end = models.DateTimeField('end date', null=True, blank=True)
    filename = models.CharField(max_length=50, null=False)
    video_id = models.CharField(max_length=20, null=True)
    stratum = models.CharField(max_length=20, null=True, blank=True)
    rotation = models.CharField(max_length=20, null=True, blank=True)
    objects_detected = models.BooleanField(default=False)
    max_confidence = models.IntegerField(default=0)
    document = models.FileField(upload_to=fn_video_location, null=True)
    uploaded_at = models.DateTimeField(auto_now_add=True, null=True)
    fps_video = models.IntegerField(null=True, blank=True)
    fps_inference = models.IntegerField(null=True, blank=True)
    video_status = models.CharField(max_length=3, choices=VideoStatus.choices, default=VideoStatus.NONE,)
    inference_model = models.CharField(max_length=20, null=True, blank=True)
    max_objects_detected = models.IntegerField(null=True, blank=True)
    video_height = models.IntegerField(null=True, blank=True)
    video_width = models.IntegerField(null=True, blank=True)

    def save(self, *args, **kwargs):
        if self.filename is None or self.filename is '':
            self.filename = ntpath.basename(self.document.path)
        if self.max_objects_detected is not None and int(self.max_objects_detected) > 0:
            self.objects_detected = True

        super(VideoFile, self).save(*args, **kwargs)


class Observation(models.Model):
    video_file = models.ForeignKey(VideoFile, on_delete=models.CASCADE)
    ob_date = models.DateTimeField('observation date')
    ob_class = models.CharField(max_length=50)
    ob_order = models.CharField(max_length=50)
    ob_genus = models.CharField(max_length=50)
    ob_species = models.CharField(max_length=50)
    ob_common_name = models.CharField(max_length=255)
    ob_count = models.IntegerField(default=0)
    ob_quality = models.IntegerField(default=0)
    ob_notes = models.CharField(max_length=4000)
    ob_observer = models.CharField(max_length=50)
    ob_observer_2 = models.CharField(max_length=50)

class VideoFrame(models.Model):
    video_file = models.ForeignKey(VideoFile, on_delete=models.CASCADE)
    frame_number = models.IntegerField(default=0)
    objects_detected = models.IntegerField(null=True, blank=True)
    filename = models.FileField()
    max_confidence = models.IntegerField(default=0)

    def videoTimestamp(self):
        return int(self.frame_number / self.video_file.fps_inference)

    def videoTimestampFormatted(self):
        video_timestamp = self.videoTimestamp()
        seconds = video_timestamp % (24 * 3600)
        hour = seconds // 3600
        seconds %= 3600
        minutes = seconds // 60
        seconds %= 60
        return "%d:%02d:%02d" % (hour, minutes, seconds)

class Prediction(models.Model):
    video_frame = models.ForeignKey(VideoFrame, on_delete=models.CASCADE)
    coord_top = models.IntegerField(default=0)
    coord_left = models.IntegerField(default=0)
    coord_bottom = models.IntegerField(default=0)
    coord_right = models.IntegerField(default=0)
    confidence = models.IntegerField(default=0)
    pred_class = models.CharField(max_length=255)

cameratrap/forms.py
from django import forms
from .models import VideoFile

class UploadFileForm(forms.ModelForm):
    document = forms.FileField(
        widget=forms.ClearableFileInput(attrs={"multiple": True })
    )

    class Meta:
        model = VideoFile
        fields = ['document','ct_id', 'site_id']

cameratrap/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from .models import VideoFile, VideoFrame
from django.shortcuts import get_object_or_404, render, redirect
from .forms import UploadFileForm
import logging
from .VideoProcessor import VideoProcessor
from cameratrap.tasks import process_video_async
from .CocoUtils import CocoUtils

class IndexView(generic.ListView):
    template_name = 'cameratrap/index.html'
    context_object_name = 'latest_video_files'
    model = VideoFile
    paginate_by = 25
    ordering = ['-uploaded_at']


class DetailView(generic.DetailView):
    model = VideoFile
    context_object_name = 'videoFile'
    template_name = 'cameratrap/detail.html'


def UploadFileView(request):
    form = UploadFileForm()
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        files = request.FILES.getlist("document")
        if form.is_valid():
            for f in files:
                #new_video_file = form.save()
                logging.debug("file upload successful ")
                instance = VideoFile(document=f)
                instance.ct_id = form.cleaned_data.get("ct_id")
                instance.site_id = form.cleaned_data.get("site_id")
                instance.video_status = VideoFile.VideoStatus.UPLOADED
                instance.save()

                logging.debug(f"processing video in the background with pkid: {instance.pk}")
                process_video_async.delay(instance.pk)
            return redirect('cameratrap:index')
    else:
        form = UploadFileForm()
    return render(request, 'cameratrap/upload.html', {
        'form': form
    })


def SyncProcessVideoView(request, video_pkid):
    print("Sync SyncProcessVideoView Called")
    video_file = VideoFile.objects.get(pk=video_pkid)
    vp = VideoProcessor(video_file)
    vp.processVideo()
    print("Sync SyncProcessVideoView Completed")
    return HttpResponseRedirect(reverse('cameratrap:detail', args=(video_pkid,)))


def ASyncProcessVideoView(request, video_pkid):
    print("ASync ASyncProcessVideoView Called")
    process_video_async.delay(video_pkid)
    print("ASync ASyncProcessVideoView Completed")
    return HttpResponseRedirect(reverse('cameratrap:detail', args=(video_pkid,)))


def CocoVideoFrameView(request, video_pkid, video_frame_pkid):
    print("CocoVideoFrameView Called")
    video_frame = VideoFrame.objects.get(pk=video_frame_pkid)
    coco_util = CocoUtils(video_frame)
    coco_util.process_frame_to_coco()
    print("CocoVideoFrameView Completed")
    return HttpResponseRedirect(reverse('cameratrap:detail', args=(video_pkid,)))

cameratrap/templates/cameratrap/detail.html
<!doctype html>
<html lang="en">
{% load static %}

{# Load the tag library #}
{% load bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<head>
    <link rel="stylesheet" href="{% static 'cameratrap/style.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>

{% include 'cameratrap/navbar.html' %}

<div class="container-lg">

    <div class="header1">
        {{ videoFile.ct_id }} - {{ videoFile.site_id }} - {{ videoFile.filename }} - Max Confidence {{ videoFile.max_confidence }}%
    </div>

    <div class="leftPane">
        <div class="embed-responsive embed-responsive-16by9">
            <video width="640" height="360" controls="true" preload="auto" id="oVideo">
              <source src="{{ videoFile.document.url }}" type="video/mp4"/>
            Your browser does not support the video tag.
            </video>
        </div>
        <div class="videoData">
            {{ videoFile.date_start }} - {{ videoFile.date_end }} {{ videoFile.video_width }} x {{ videoFile.video_height }} @ {{ videoFile.fps_video }} fps
        </div>
        <div class="videoMetadata">
            Status: {{ videoFile.video_status }}<br/>
            Objects Detected: {{ videoFile.objects_detected }} <br/>
            Max Objects: {{ videoFile.max_objects_detected }}<br/>
            Max Confidence: {{ videoFile.max_confidence }}<br/>
            Model:{{ videoFile.inference_model }}<br/>
            IFPS: {{ videoFile.fps_inference }}<br/>
        </div>
    </div>

    <div class="rightPane">
        {% for vFrame in videoFile.videoframe_set.all|dictsortreversed:"max_confidence" %}
            <div class="vFrameHolder">
                <a href="#" id="linkJumpToFrame_{{ vFrame.pk }}" onclick="document.getElementById('oVideo').currentTime={{ vFrame.videoTimestamp }}">
                    <img height=256 src="{{ vFrame.filename.url }}"/><br/>
                </a>
                <div class="frameMetadata">
                    Frame {{ vFrame.frame_number }} - ({{ vFrame.videoTimestampFormatted }}) -
                    Confidence: {{ vFrame.max_confidence }}%
                    <a href="{% url 'cameratrap:coco' videoFile.id vFrame.id%}">CoCo</a> -

                </div>
            </div>
        {% endfor %}
    </div>

<div style="clear:both"></div>
<hr/>
    <a href="{% url 'cameratrap:process' videoFile.id %}">Reprocess {{ videoFile.filename }} Sync</a><br/>
    <a href="{% url 'cameratrap:asyncprocess' videoFile.id %}">Reprocess {{ videoFile.filename }} Async</a>
</div>

cameratrap/templates/cameratrap/index.html
<!doctype html>
<html lang="en">
{% load static %}

{# Load the tag library #}
{% load bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<head>
    <link rel="stylesheet" href="{% static 'cameratrap/style.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>

{% include 'cameratrap/navbar.html' %}

<div class="container-lg">
    {% if page_obj %}
        <ul>
        {% for video_file in page_obj %}
            <li>
                <a href="{% url 'cameratrap:detail' video_file.id %}">{{ video_file.filename }}</a> -
                Confidence: {{ video_file.max_confidence }}% - {{  video_file.video_status_readable }}
            </li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No Videos are available.</p>
    {% endif %}
</div>

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>


</body>

</html>

cameratrap/templates/cameratrap/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">CameraTrap Detector</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'cameratrap:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cameratrap:upload' %}">Upload</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

cameratrap/templates/cameratrap/upload.html
<!doctype html>
<html lang="en">
{% load static %}

{# Load the tag library #}
{% load bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<head>
    <link rel="stylesheet" href="{% static 'cameratrap/style.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Upload File</title>
</head>

{% include 'cameratrap/navbar.html' %}

<body>
    <div class="container-lg">
        <div>Upload Video</div>
        <div class="jumbotron">
            {% block replace %}
            <p class="lead">Here is where you upload a file</p>
            <hr class="my-4">
            <form method="POST" enctype="multipart/form-data">
                <!-- Very Important csrf Token -->
                {% csrf_token %}
                <table>
                    {{ form.as_table }}
                </table>
                <button type="submit">Upload</button>
            </form>
        </div>
        {% endblock %}
    </div>
</body>

</html>